sudo: required
services:
  - docker

script:
  - docker build -t hemanshi163/node .
  - docker images hemanshi163/node

before_deploy:
  - docker login -u hemanshi163 -p Cpp@123

deploy:
  provider: script
  script: docker push hemanshi163/node
  on: 
    branch: master
